# Generated by Django 6.0.2 on 2026-03-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_by_product_updated_by'),
        ('suppliers', '0002_supplier_balance_supplier_country_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier'),
        ),
    ]
