# Generated by Django 6.0.2 on 2026-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
